CUDA_VISIBLE_DEVICES="0,1" python train_recammaster_packed.py  \
    --task train  \
    --dataset_path ./trainset  \
    --output_path ./models  \
    --text_encoder_path "models/Wan-AI/Wan2.1-T2V-1.3B/models_t5_umt5-xxl-enc-bf16.pth"  \
    --vae_path "models/Wan-AI/Wan2.1-T2V-1.3B/Wan2.1_VAE.pth"  \
    --dit_path "models/Wan-AI/Wan2.1-T2V-1.3B/diffusion_pytorch_model.safetensors"  \
    --tiled  \
    --num_frames 81  \
    --height 640  \
    --width 640 \
    --dataloader_num_workers 2 \
    --max_epochs 5 \
    --use_gradient_checkpointing_offload \
    --use_gradient_checkpointing \
    --resume_ckpt_path ./models/ReCamMaster/checkpoints/step20000.ckpt \